name: "test"
on:
  push:
    # tags: ["v[0-9]+.[0-9]+.[0-9]+*"]
    branches: [main]

env:
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  CARGO_TERM_COLOR: always
  RUST_TOOLCHAIN: 1.92.0

jobs:
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6
      - name: setup node
        uses: actions/setup-node@v6
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}
      - name: Install target
        run: |
          rustup update
          rustup target add aarch64-apple-darwin
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          key: macos-build
      - name: release
        run: |
          cargo install cargo-bundle
          cargo bundle --release  --features mimalloc
          ls -lh target/release/bundle/osx
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6
      - name: setup node
        uses: actions/setup-node@v6
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          target: x86_64-pc-windows-msvc
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          key: windows-build
      - name: release
        run: |
          cargo build --release  --features mimalloc
          ls -lh target/release
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: setup node
        uses: actions/setup-node@v6
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          target: x86_64-unknown-linux-gnu
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          key: linux-build
      - name: release
        run: |
          cargo build --release  --features mimalloc
          ls -lh target/release